Company_library/urls.py
from django.contrib import admin
from django.urls import path
from comp_lib.views import LibraryView, BookListView, BookSearchView, BookDetailView, BookAddView, BookDeleteView,\
    AddUserView, LoginView, LogoutView, LoanedBooksByUserListView, AvailableBooksListView, LoanedBooksListView,\
    BookHistoryListView, BookDetailHistoryListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LibraryView.as_view(), name="library"),
    path('books/', BookListView.as_view(), name="books"),
    path('search/', BookSearchView.as_view(), name="book-search"),
    path('book/<int:book_id>', BookDetailView.as_view(), name="book"),
    path('add/', BookAddView.as_view(), name="book-add"),
    path("book/<int:book_id>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("add_user/", AddUserView.as_view(), name="add-user"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("my_books/", LoanedBooksByUserListView.as_view(), name="loaned-list"),
    path("available/", AvailableBooksListView.as_view(), name="available-list"),
    path("loans/", LoanedBooksListView.as_view(), name="list-loaned"),
    path("history/", BookHistoryListView.as_view(), name="history"),
    path("book/<int:book_id>/history/", BookDetailHistoryListView.as_view(), name="book-history"),

]

comp_lib/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from simple_history.models import HistoricalRecords

# Create your models here.
class Book(models.Model):
    """Model representing a book that can be borrowed from the library."""
    number = models.CharField(max_length=9,
                          help_text="Year/number: YYYY/num", unique=True)
    name = models.CharField(max_length=200)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    borrowed_on = models.DateField(null=True, blank=True)
    is_available = models.BooleanField(blank=True, default=True, help_text='Dostępność książki')
    history = HistoricalRecords()
    created = models.DateField(null=True, blank=True)
    modified = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.number, self.name)

comp_lib/forms.py
from django import forms
from .models import Book
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .validators import validate_username, validate_email

class BookSearchForm(forms.Form):
    name = forms.CharField(label="Podaj tytuł",
                           help_text="Wprowadź tytuł bądź jego fragment, by wyszukać książkę")

class BookAddForm(forms.Form):
    number = forms.CharField(label="Nr inw.",
                           help_text="Rok/numer: YYYY/num")
    name = forms.CharField(label="Tytuł",
                                help_text="Podaj tytuł")


class AddUserForm(forms.Form):
    username = forms.CharField(max_length=50, label="Nazwa użytkownika", validators=[validate_username])
    password = forms.CharField(widget=forms.PasswordInput, label="Hasło")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Powtórz hasło")
    first_name = forms.CharField(label="Imię")
    last_name = forms.CharField(label="Nazwisko")
    email = forms.EmailField(label="E-mail", validators=[validate_email])

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data["password"] != cleaned_data["password2"]:
            raise forms.ValidationError("Podane hasła nie są identyczne!")

class LoginForm(forms.Form):
    username = forms.CharField(label="Nazwa użytkownika")
    password = forms.CharField(widget=forms.PasswordInput, label="Hasło")

comp_lib/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import View
from .models import Book, HistoricalRecords
from django.contrib.auth.models import User, Permission
from .forms import BookSearchForm, BookAddForm, AddUserForm, LoginForm
from django.views.generic import DetailView, DeleteView, ListView
from datetime import date


class LibraryView(View):

    def get(self, request):
        num_books = Book.objects.all().count()
        num_books_available = Book.objects.filter(is_available=True).count()
        return render(request, "index.html", {
            "num_books": num_books,
            "num_books_available": num_books_available}
                      )


class BookListView(View):
    def get(self, request):
        books = Book.objects.all()
        return render(request, "books.html", {"books": books})


class BookSearchView(View):

    def get(self, request):
        form = BookSearchForm()
        ctx = {
            "form": form,
        }
        return render(request, "book_search.html", ctx)

    def post(self, request):
        form = BookSearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            results = Book.objects.filter(name__icontains=name)
            ctx = {
                "form": form,
                "results": results,
            }
            return render(request, "book_search.html", ctx)


class BookDetailView(View):

    def get(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)
        ctx = {
            "book": book,
        }
        return render(request, "book.html", ctx)

    def post(self, request, book_id):
        if request.POST.get('loan'):
            book = get_object_or_404(Book, id=book_id)
            current_user = request.user
            book.is_available = False
            book.borrower = current_user
            book.borrowed_on = date.today()
            book.save()
            return redirect("book", book_id=book.id)
        elif request.POST.get('return'):
            book = get_object_or_404(Book, id=book_id)
            book.is_available = True
            book.borrower = None
            book.borrowed_on = None
            book.save()
            return redirect("book", book_id=book.id)


class BookAddView(View, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, request):
        if request.user.is_superuser:
            form = BookAddForm()
            return render(request, "book_add.html", {"form": form})
        else:
            return redirect("books")

    def post(self, request):
        form = BookAddForm(request.POST)
        if form.is_valid():
            book = Book.objects.create(
                number=form.cleaned_data["number"],
                name=form.cleaned_data["name"]
            )
            return redirect("book", book_id=book.id)
        return render(request, "book_add.html", {"form": form})


class BookDeleteView(DeleteView, UserPassesTestMixin):
    model = Book
    template_name = "book_delete.html"
    pk_url_kwarg = "book_id"

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
            book_id = self.kwargs["book_id"]
            context = super().get_context_data(**kwargs)
            context["book"] = get_object_or_404(Book, pk=book_id)
            return context

    def get_success_url(self):
        return reverse("books")


class AddUserView(View):

    def get(self, request):
        form = AddUserForm()
        return render(request, "add_user.html", {"form": form})

    def post(self, request):
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.cleaned_data.pop("password2")
            user = get_user_model().objects.create_user(**form.cleaned_data)
            return redirect("/")
        return render(request, "add_user.html", {"form": form})


class LoginView(View):

    def get(self, request):
        form = LoginForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(**form.cleaned_data)
            if user is not None:
                login(request, user)
                return redirect("/")
        return render(request, "login.html", {"form": form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        return redirect("/")


class LoanedBooksByUserListView(LoginRequiredMixin, ListView):

    model = Book
    template_name = 'list_loaned_user.html'

    def get_queryset(self):
        return Book.objects.filter(borrower=self.request.user)


class AvailableBooksListView(ListView):

    model = Book
    template_name = 'list_available.html'

    def get_queryset(self):
        return Book.objects.filter(is_available=True)


class LoanedBooksListView(ListView):

    model = Book
    template_name = 'list_loaned.html'

    def get_queryset(self):
        return Book.objects.filter(is_available=False)


class BookHistoryListView(ListView):
    template_name = "history.html"

    def get_queryset(self):
        history = Book.history.all()
        return history


class BookDetailHistoryListView(ListView):
    template_name = "book_history.html"
    context_object_name = 'book_history'

    def get_queryset(self):
        book_history = Book.history.filter(id=self.kwargs['book_id'])
        return book_history

comp_lib/templates/add_user.html
{% extends "base.html" %}
{% block title %}Dodaj użytkownika{% endblock %}

{% block content %}
<form action="{% url 'add-user' %}" method="POST">
    {% csrf_token %}
    <table>
    {{ form }}
        </table>
    <input type="submit" class="small blue button" value="Dodaj">
</form>


{% endblock %}

comp_lib/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'css/lib.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
<link rel="stylesheet" href="{% static 'css/table.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
       <body>
            <div class="hero-nav">
                <div class="hero-nav__inner">
                    <h1>Biblioteka Zakładowa</h1>
                    <h1>Light Code Sp. z.o.o.</h1>
                </div>
            </div>
                {% block content %}
                {% endblock %}


            <hr />
            {% if user.is_authenticated %}
    Zalogowany jako: {{ user }} <a class="small blue button" href="{% url 'logout' %}">WYLOGUJ</a>
{% else %}
    Niezalogowany <a class="small blue button" href="{% url 'login' %}">LOGOWANIE</a>
                lub <a class="small blue button" href="{% url 'add-user' %}">REJESTRACJA</a>
{% endif %}

            </body>
</html>

comp_lib/templates/book.html
{% extends "base.html" %}
{% block title %}Książka {{ book }}{% endblock %}

{%block content %}
<br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
<form action="" method="post">
{% csrf_token %}
{% if user.is_authenticated and book.is_available %}
    <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td>{{ book.number }}</td>
<td>{{ book.name }}</td>
{% if book.is_available %}
        <td>Dostępna</td>
{% else %}
        <td>Wypożyczona</td>
{%  endif %}
</tr>
  </tbody>
</table>

<input type="submit" class="small blue button" name="loan" value="Wypożycz">

{% elif user.is_authenticated and book.is_available != 'true' and user == book.borrower %}
<table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Wypożyczona przez</th>
            <th>Wypożyczona dnia</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td>{{ book.number }}</td>
<td>{{ book.name }}</td>
<td>{{ book.borrower.get_full_name }}</td>
<td>{{ book.borrowed_on }}</td>
{% if book.is_available %}
        <td>Dostępna</td>
{% else %}
        <td>Wypożyczona</td>
{%  endif %}
</tr>
  </tbody>
</table>
<tbody>

<input type="submit" class="small blue button" name="return" value="Oddaj książkę">

{% elif user.is_authenticated and book.is_available != 'true' %}
<table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Wypożyczona przez</th>
            <th>Wypożyczona dnia</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td>{{ book.number }}</td>
<td>{{ book.name }}</td>
<td>{{ book.borrower.get_full_name }}</td>
<td>{{ book.borrowed_on }}</td>
{% if book.is_available %}
        <td>Dostępna</td>
{% else %}
        <td>Wypożyczona</td>
{%  endif %}
</tr>
  </tbody>
</table>
{% elif user.is_authenticated != 'true' %}
<table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
<tr>
<td>{{ book.number }}</td>
<td>{{ book.name }}</td>
{% if book.is_available %}
        <td>Dostępna</td>
{% else %}
        <td>Wypożyczona</td>
{%  endif %}
</tr>
  </tbody>
</table>
{% endif %}
{% if request.user.is_superuser %}
        <a class="small blue button" href="{% url 'book-delete' book.id %}">Usuń książkę</a>
        <a class="small blue button" href="{% url 'book-history' book.id %}">Historia wypożyczeń</a>
    {% endif %}
</form>
{% endblock %}

comp_lib/templates/book_add.html
{% extends "base.html" %}
{% block title %}Dodaj książkę{% endblock %}

{% block content %}
<br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
</br><br>
<form action="{% url 'book-add' %}" method="POST">
    {% csrf_token %}
    <table>
    {{ form }}
        </table>
    {% if request.user.is_superuser %}
    <input type="submit" class="small blue button" value="Dodaj">
    {% else %}
    <p>Nie masz wymaganych uprawnień</p>
    {% endif %}
</form>


{% endblock %}

comp_lib/templates/book_delete.html
{% extends "base.html" %}
{% block title %}Usuń książkę{% endblock %}

{% block content %}
<br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
<form action="{% url 'book-delete' book.id %}" method="POST">
    {% csrf_token %}
    <table>
    {{ form }}
        <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ book.number }}</td>
         <td>{{ book.name }}</td>
        {% if book.is_available %}
            <td>Dostępna</td>
        {% else %}
            <td>Wypożyczona</td>
        {%  endif %}
        </tr>
            </tbody>
</table>
    {% if request.user.is_superuser %}
    <input type="submit" class="small blue button"value="Usuń">
    {% else %}
    <p>Nie masz uprawnień do usuwania książek</p>
    {% endif %}
</form>


{% endblock %}

comp_lib/templates/book_history.html
{% extends "base.html" %}
{% block title %}Historia wypożyczeń{% endblock %}

{%block content %}

    <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
{% if request.user.is_superuser %}
<h2>Historia:</h2>
    <table class="styled-table">
    <thead>
        <tr>
            <th>Tytuł</th>
            <th>Wypożyczający</th>
            <th>Data/Godzina</th>
            <th>Użytkownik</th>
            <th>Typ akcji</th>
        </tr>
    </thead>
    <tbody>
 {% for t in book_history %}
        <tr>
            <td>{{ t.name }}</td>
            <td>{{ t.borrower.get_full_name }}</td>
            <td>{{ t.history_date }}</td>
            <td>{{ t.history_user.get_full_name }}</td>
            {% if t.get_history_type_display == 'Created' %}
                <td>Dodana</td>
            {% elif t.get_history_type_display == 'Deleted' %}
                <td>Usunięta</td>
            {% elif t.is_available %}
                <td>Zwrócona</td>
            {% else %}
                <td>Wypożyczona</td>
            {% endif %}

        </tr>
        {% endfor %}
        </tbody>
</table>
{% endif %}
{% endblock %}

comp_lib/templates/book_search.html
{% extends "base.html" %}
{% block title %}Wyszukiwarka książek{% endblock %}

{% block content %}
        <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
    </br><br>
<form action="{% url 'book-search' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input class="small blue button" type="submit" value="Szukaj">
</form>
<table class="styled-table">
{% if results %}
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
        {% for book in results %}
            <tr>
        <td><a href="/book/{{ book.id }}">{{ book.number }}</a></td><td> {{ book.name }}</td>
         {% if book.is_available %}
            <td>Dostępna</td>
        {% else %}
            <td>Wypożyczona</td>
        {%  endif %}
        {% endfor %}
     </tbody>
</table>
{% else %}
    <p>Brak książek</p>
{% endif %}
{% endblock %}

comp_lib/templates/books.html
{% extends "base.html" %}
{% block title %}Lista książek{% endblock %}

{%block content %}
    <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
<h2>Zbiory biblioteki:</h2>
    <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Dostępność</th>
        </tr>
    </thead>
    <tbody>
{% if books %}

    {% for book in books %}
        <tr>
        <td><a href="/book/{{ book.id }}">{{ book.number }}</a></td>
        <td> {{ book.name }}</td>
         {% if book.is_available %}
            <td>Dostępna</td>
        {% else %}
            <td>Wypożyczona</td>
        {%  endif %}
        </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>Brak książek</p>
{% endif %}
{% endblock %}

comp_lib/templates/history.html
{% extends "base.html" %}
{% block title %}Historia wypożyczeń{% endblock %}

{%block content %}

    <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
{% if request.user.is_superuser %}
<h2>Historia:</h2>
    <table class="styled-table">
    <thead>
        <tr>
            <th>Tytuł</th>
            <th>Wypożyczający</th>
            <th>Data/Godzina</th>
            <th>Użytkownik</th>
            <th>Typ akcji</th>
        </tr>
    </thead>
    <tbody>
 {% for t in object_list %}
        <tr>
            <td>{{ t.name }}</td>
            <td>{{ t.borrower.get_full_name }}</td>
            <td>{{ t.history_date }}</td>
            <td>{{ t.history_user.get_full_name }}</td>
            {% if t.get_history_type_display == 'Created' %}
                <td>Dodana</td>
            {% elif t.get_history_type_display == 'Deleted' %}
                <td>Usunięta</td>
            {% elif t.is_available %}
                <td>Zwrócona</td>
            {% else %}
                <td>Wypożyczona</td>
            {% endif %}

        </tr>
        {% endfor %}
        </tbody>
</table>
{% endif %}
{% endblock %}

comp_lib/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Strona główna{% endblock %}

{% block content %}
    <h1><strong>Zbiory biblioteki:</strong></h1>
<ul style="list-style-type:none;">
    <li>Ilość książek: {{num_books}}</li>
    <li>Ilość aktualnie dostępnych książek: <a href="{%  url 'available-list' %}">{{num_books_available}}</a></li>
</ul>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
       <div class="inner"><a class="large blue button" href="{% url 'books' %}">LISTA KSIĄŻEK</a></div>
   <div class="inner"><a class="large blue button" href="{% url 'book-search' %}">WYSZUKAJ KSIĄŻKĘ</a></div>
{% if user.is_authenticated %}
<a class="large blue button" href="{% url 'loaned-list' %}">Moje wypożyczenia</a>
{%  endif %}
    {% if request.user.is_superuser %}
        <a class="large blue button" href="{% url 'book-add' %}">Dodaj książkę</a>
        <a class="large blue button" href="{% url 'list-loaned' %}">Wypożyczenia</a>
        <a class="large blue button" href="{% url 'history' %}">Historia</a>
    {% endif %}
{% endblock %}

comp_lib/templates/list_available.html
{% extends "base.html" %}
{% block title %}Dostępne książki{% endblock %}

{% block content %}
            <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
    <h2>Dostepne książki</h2>
{% if book_list %}
    <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
        </tr>
    </thead>
    <tbody>
        {% for book in book_list %}
            <tr>
            <td><a href="/book/{{ book.id }}">{{  book.number }}</a></td>
            <td>{{ book.name }}</td>
            </tr>
        {% endfor %}
 </tbody>
</table>
{% else %}
<p>Brak dostępnych książek</p>
{% endif %}
</form>


{% endblock %}

comp_lib/templates/list_loaned.html
{% extends "base.html" %}
{% block title %}Wypożyczone książki{% endblock %}

{% block content %}
            <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
    <h2>Wypożyczone książki</h2>
{% if book_list %}
    <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
            <th>Wypożyczona przez</th>
        </tr>
    </thead>
    <tbody>
        {% for book in book_list %}
        <tr>
            <td><a href="/book/{{ book.id }}">{{  book.number }}</a></td>
            <td> {{ book.name }}</td>
            <td>{{ book.borrower.get_full_name }}</td>
        </tr>
        {% endfor %}
  </tbody>
</table>
{% else %}
<p>Brak wypożyczeń</p>
{% endif %}
</form>


{% endblock %}

comp_lib/templates/list_loaned_user.html
{% extends "base.html" %}
{% block title %}Wypożyczenia{% endblock %}

{% block content %}
            <br>
<a class="small blue button" href="{% url 'library' %}">Powrót do Strony Głównej</a>
<form action="{% url 'loaned-list' %}" method="POST">
    {% csrf_token %}
    <h2>Wypożyczone książki</h2>
{% if book_list %}
    <table class="styled-table">
    <thead>
        <tr>
            <th>Indeks</th>
            <th>Tytuł</th>
        </tr>
    </thead>
    <tbody>
        {% for book in book_list %}
            <tr>
            <td><a href="/book/{{ book.id }}">{{  book.number }}</a></td>
            <td>{{ book.name }}</td>
            </tr>
        {% endfor %}
      </tbody>
</table>
{% else %}
<p>Brak wypożyczeń</p>
{% endif %}
</form>


{% endblock %}

comp_lib/templates/login.html
{% extends "base.html" %}
{% block title %}Logowanie{% endblock %}

{% block content %}
<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <table>
    {{ form }}
        </table>
    <input type="submit" class="small blue button" value="Zaloguj">
</form>


{% endblock %}